### ISSUE TITLE
the ERR_TOO_MANY_REDIRECTS issue

### ISSUE THREAD

**Issue by hiproz** [XGowe/GoogleMirror#2]
i want to use gmail and google map ,so i unmask the line 20 and 32 of public.php:

"(([a-z0-9-]+).google.com)" => "$1." . $pHost,

"(([a-z0-9-]+)." . preg_quote($pHost) . ")" => "$1.google.com",

 ,it appear ERR_TOO_MANY_REDIRECTS  , can anyone give me some guides for resolve it. thanks

**Comment by Gowee** [comment]
Hello, hiproz

I feel sorry that I did not notice your issue because I did not get any email for notification of your issue from GitHub. Thus I did not reply in time.

Gmail is too complicated to deal with, thus it is hard to support gmail. If you want to "proxy" gmail, I suggest that you use RainLoop or other programs.

But it should work well with google map, ERR_TOO_MANY_REDIRECTS often dues to the HTTP "Host:" header sent to the original server. Please check the "Host:" sent to the original server when you requested (e.g print out the $curlRequestHeaders). If you get stuck with it, please tell me.

And the program currently needs *.yourdomain.com to perform with the *.originaldomain.com (i.e *.google.com as mentioned by you), although I do not think is a good idea, but it is easy to code and handle the complex cookie problem. So you need to make sure this point (proper domain record).

Besides, this version [#76045fe](../commit/76045fe0b0ce73ec71ff34678bc3828c72056c64) is closely coupled with www.google.com , and it is not easy to seperate it, because many parted are simplified or specially set to make it work with www.google.com (the search part). If you would like to use it to "proxy" other part of google, such as maps.google.com, I think it is a good idea to use the previous version.

Particularly, for Google Maps (maps.google.com) which you can use the URL https://www.google.com/map to visit it, you does not modify this part which you mentioned above. The only thing needed is to use https://www.yourproxieddomain.com/maps instead of https://maps.yourproxieddomain.com, which needs extra configuration, to visit Google Maps.

Last but no least, I am busy rencently, and the result is I have no plan to update or maintain this programs recently ( or probably no longer ). I only got a partly deprecated another new version which previsouly was modified several months ago. So please be careful if you want to use this in important environment. And I recommend you to use other similar programs rather to complete similar functionalities. (Such as [this Nginx Module](https://github.com/cuber/ngx_http_google_filter_module) also open-sourced on GitHub, modification is also needed to support Gmail and etc.) However, I am always here, if you have any further problems or need any helps I can provide with, you can just reply here or open another issue.

Nice day,
Gowe

**Comment by hiproz** [comment]
thanks for your work and reply:)
